### ISSUE TITLE
Iphone 5

### ISSUE THREAD

**Issue by jrlopes2005** [ooper-shlab/GLPaint1.13-Swift#1]
This doesn´t work on  iPhone 5 simulator, what  should i do?

**Comment by jrlopes2005** [comment]
This doesn´t work on iPhone 5 simulator, what i should do?

**Comment by ooper-shlab** [comment]
Thanks for having interest in my translated sample code.

But you need to be more specific when you report "doesn't work" issues. It actually works on iPhone5 simulator in my environment, so I have no clue just told "doesn't work".

**Comment by jrlopes2005** [comment]
If i run your code on iphone 5 simulator and older versions of iphone, i can´t draw on the screen, but if i test on 5s,6,6s.. i can draw and works fine.

**Comment by jrlopes2005** [comment]
Sorry my mistake, your code works for allsimulators

**Comment by ooper-shlab** [comment]
Thanks for your reply. Please don't be afraid of mistakes and tell me when you find other problems.
(Just have in mind that I cannot assure you if I would be able to fix all such issues.)
