### ISSUE TITLE
iOS 10 / Swift 3 ....

### ISSUE THREAD

**Issue by leedashone** [ooper-shlab/GLPaint1.13-Swift#2]
Dears,

Is it possible upgrade to compatible Swift 3 / iOS 10 / XCode 8 ?
I try to modify, but too many OpenGL error...  
(I don't know too much about OpenGL)

Many Thanks!

**Comment by ooper-shlab** [comment]
OK, I'll put this project at the top of my adapt-to-Swif3 queue.

**Comment by ooper-shlab** [comment]
Done. Please try.

**Comment by leedashone** [comment]
The code works perfect! many many THANKS !!!!  ;-)

**Comment by ooper-shlab** [comment]
Thanks for reporting. If you find some faults later, please notify me as another issue.
